name: fitto
description: "Fitto is a modern fitness and nutrition app, inspired by wger Flutter, designed to help you effortlessly track workouts, nutrition, and progress with a sleek, no-code friendly UI and a sprinkle of AI-powered motivation."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  share_plus: ^12.0.0
  timezone: 0.10.1
  flutter_local_notifications: ^19.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  fl_chart: 0.68.0
  intl: 0.20.2
  provider: ^6.1.1
  shimmer: ^3.0.0
  http: ^1.1.0
  uuid: ^4.2.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
