class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Fitto',
      'welcome': 'Welcome to Fitto',
      'start': 'Get Started',
      'sign_in_google': 'Sign in with Google',
      'sign_in_apple': 'Sign in with Apple',
      'home': 'Home',
      'workouts': 'Workouts',
      'nutrition': 'Nutrition',
      'progress': 'Progress',
      'coach': 'AI Coach',
      'settings': 'Settings',
      'premium': 'Premium',
      'daily_summary': 'Daily Summary',
      'calories': 'Calories',
      'water': 'Water',
      'steps': 'Steps',
      'motivation_quote': 'Motivation of the Day',
      'add_workout': 'Add Workout',
      'suggest_workout': 'AI Suggest Workout',
      'add_meal': 'Add Meal',
      'ai_food_scan': 'AI Food Recognition',
      'weight': 'Weight',
      'profile': 'Profile',
      'language': 'Language',
      'theme': 'Theme',
      'notifications': 'Notifications',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'lifetime': 'Lifetime',
      'subscribe': 'Subscribe',
      'onboarding_title_1': 'Track Your Fitness',
      'onboarding_desc_1': 'Monitor your workouts, nutrition, and progress all in one place',
      'onboarding_title_2': 'Stay Motivated',
      'onboarding_desc_2': 'Get daily motivation and personalized coaching from AI',
      'onboarding_title_3': 'Achieve Your Goals',
      'onboarding_desc_3': 'Set goals, track progress, and celebrate your achievements',
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'snacks': 'Snacks',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fats': 'Fats',
      'chat_placeholder': 'Ask your AI coach...',
      'send': 'Send',
      'water_tracker': 'Water Tracker',
    },
    'tr': {
      'app_name': 'Fitto',
      'welcome': 'Fitto\'ya Hoş Geldiniz',
      'start': 'Başla',
      'sign_in_google': 'Google ile Giriş Yap',
      'sign_in_apple': 'Apple ile Giriş Yap',
      'home': 'Ana Sayfa',
      'workouts': 'Antrenmanlar',
      'nutrition': 'Beslenme',
      'progress': 'İlerleme',
      'coach': 'AI Koç',
      'settings': 'Ayarlar',
      'premium': 'Premium',
      'daily_summary': 'Günlük Özet',
      'calories': 'Kalori',
      'water': 'Su',
      'steps': 'Adım',
      'motivation_quote': 'Günün Motivasyonu',
      'add_workout': 'Antrenman Ekle',
      'suggest_workout': 'AI Antrenman Öner',
      'add_meal': 'Öğün Ekle',
      'ai_food_scan': 'AI Yemek Tanıma',
      'weight': 'Kilo',
      'profile': 'Profil',
      'language': 'Dil',
      'theme': 'Tema',
      'notifications': 'Bildirimler',
      'light': 'Açık',
      'dark': 'Koyu',
      'system': 'Sistem',
      'monthly': 'Aylık',
      'yearly': 'Yıllık',
      'lifetime': 'Ömür Boyu',
      'subscribe': 'Abone Ol',
      'onboarding_title_1': 'Formunuzu Takip Edin',
      'onboarding_desc_1': 'Antrenmanlarınızı, beslenmenizi ve ilerlemenizi tek yerde izleyin',
      'onboarding_title_2': 'Motive Kalın',
      'onboarding_desc_2': 'Yapay zekadan günlük motivasyon ve kişiselleştirilmiş koçluk alın',
      'onboarding_title_3': 'Hedeflerinize Ulaşın',
      'onboarding_desc_3': 'Hedefler belirleyin, ilerlemenizi takip edin ve başarılarınızı kutlayın',
      'breakfast': 'Kahvaltı',
      'lunch': 'Öğle Yemeği',
      'dinner': 'Akşam Yemeği',
      'snacks': 'Atıştırmalık',
      'protein': 'Protein',
      'carbs': 'Karbonhidrat',
      'fats': 'Yağ',
      'chat_placeholder': 'AI koçunuza sorun...',
      'send': 'Gönder',
      'water_tracker': 'Su Takibi',
    },
  };

  static String get(String key, String locale) => _localizedValues[locale]?[key] ?? key;
}
